### ISSUE TITLE
IPFS Importer/Exporter Master Issue

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#139]
This is a master issue to track work on understanding why the IPFS importer/exporter packages don't reliably work for us.

 - [x] #114 - Main description of the problem
 - [x] #129 - Create a minimum failing test to show to IPFS maintainers
 - [x] #141 - Once a V1 CID is successfully retrieved from a storage miner, it cannot be re-shared on the browser network
